FusionIIIT-master/FusionIIIT-master/FusionIIIT/Fusion/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls',
                                          namespace='procedures')),
    #url(r'^check/',include('applications.complaint_system.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FusionIIIT-master/FusionIIIT-master/FusionIIIT/applications/central_mess/urls.py
from django.conf.urls import url

from . import views

app_name = 'mess'

urlpatterns = [

    url(r'^', views.mess, name='mess'),

]

FusionIIIT-master/FusionIIIT-master/FusionIIIT/applications/eis/urls.py
from django.conf.urls import url

from . import views

app_name = 'eis'

urlpatterns = [

    url(r'^profile/', views.profile, name='profile'),

]

FusionIIIT-master/FusionIIIT-master/FusionIIIT/applications/globals/urls.py
from django.conf.urls import url

from . import views

app_name = 'globals'

urlpatterns = [

    url(r'^$', views.index, name='index'),

    url(r'^login/', views.login, name='login'),

    url(r'^dashboard/', views.dashboard, name='dashboard'),

]

FusionIIIT-master/FusionIIIT-master/FusionIIIT/applications/leave/urls.py
from django.conf.urls import url

from . import views

app_name = 'leave'

urlpatterns = [

    url(r'^', views.leave, name='leave'),

]

FusionIIIT-master/FusionIIIT-master/FusionIIIT/templates/dashboard/alerts.html
{% load static %}

{% block alerts %}
    {% comment %}The Alerts start here!{% endcomment %}
    <div class="ui fluid card" style="padding-top: 12px; padding-bottom: 24px;">
        <a class="ui top attached black label">
            <span class="ui inverted header">
                Alerts
            </span>
            <i class="setting icon right floated"></i>
            <i class="chevron up icon right floated"></i>
        </a>

        <div class="content alerts" style="max-height: 75vh; overflow-y: auto;">
            <div class="ui animated list">
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% comment %}The Alerts ends here!{% endcomment %}
{% endblock %}

FusionIIIT-master/FusionIIIT-master/FusionIIIT/templates/dashboard/calendar.html
{% load static %}

{% block calendar %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'Fusion/css/calendar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Fusion/css/custom_2.css' %}">

    <div class="ui container grid">
        <div class="row">
            <div class="ten wide column">
                <section class="main left floated">
                    <div class="custom-calendar-wrap">
                        <div id="custom-inner" class="custom-inner">
                            <div class="custom-header clearfix">
                                <nav>
                                    <span id="custom-prev" class="custom-prev"></span>
                                    <span id="custom-next" class="custom-next"></span>
                                </nav>
                                <h2 id="custom-month" class="custom-month"></h2>
                                <h3 id="custom-year" class="custom-year"></h3>
                            </div>
                            <div id="calendar" class="fc-calendar-container"></div>
                        </div>
                    </div>
                    <div>

                    </div>
                </section>
            </div>

            <div class="six wide column">
                <div class="sideBar">
                    <h2 style="padding-bottom: 12px;">
                        Planner
                    </h2>

                    <div class="notibox">
                        Headbutt a Lion!
                        <div class="cancel">✕</div>
                    </div>

                    <div class="notibox">
                        Do Laundry
                        <div class="cancel">✕</div>
                    </div>

                    <div class="notibox">
                        Feed the Cat
                        <div class="cancel">✕</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="" style="position:absolute; left:350px; top:10px"><div class="" ></div></div>


    </div><!-- /container -->

{% endblock %}

FusionIIIT-master/FusionIIIT-master/FusionIIIT/templates/dashboard/contacts.html
{% load static %}

{% block contacts %}
    {% comment %}The Modules start here!{% endcomment %}
    <div class="ui fluid card" style="padding-top: 12px; padding-bottom: 24px;">
        <a class="ui top attached black label">
            <span class="ui inverted ui header">Contacts</span>
            <i class="setting icon right floated"></i>
            <i class="chevron up icon right floated"></i>
        </a>

        <div class="content contactContent" style="max-height: 75vh; overflow-y: auto;">
            <div class="ui middle aligned animated list">

                <div class="ui top attached tabular menu">
                    <a class="active item" data-tab="first">Faculty</a>
                    <a class="item" data-tab="second">Staff</a>
                </div>

                <div class="ui bottom attached active tab segment" data-tab="first">
                    <div class="ui fluid icon input">
                        <input placeholder="Search ..." type="text">
                        <i class="search icon"></i>
                    </div>

                    <div class="ui divider"></div>

                    <div class="item">
                        <div class="right floated tiny teal ui button">
                            <i class="mail icon"></i>Send Mail
                        </div>
                        <div class="right floated tiny blue ui button hidden-phone">
                            <i class="phone icon"></i>773-338-7786
                        </div>
                        <div class="content">
                            <img class="ui avatar image" src="{% static 'Fusion/img/zlatan.jpg' %}">
                            <a class="ui header">Atul Gupta</a>
                        </div>
                        <div class="ui divider"></div>
                    </div>


                    <div class="item">
                        <div class="right floated tiny teal ui button">
                            <i class="mail icon"></i>Send Mail
                        </div>
                        <div class="right floated tiny blue ui button hidden-phone">
                            <i class="phone icon"></i>773-338-7786
                        </div>
                        <div class="content">
                            <img class="ui avatar image" src="{% static 'Fusion/img/zlatan.jpg' %}">
                            <a class="ui header">Atul Gupta</a>
                        </div>
                        <div class="ui divider"></div>
                    </div>


                    <div class="item">
                        <div class="right floated tiny teal ui button">
                            <i class="mail icon"></i>Send Mail
                        </div>
                        <div class="right floated tiny blue ui button hidden-phone">
                            <i class="phone icon"></i>773-338-7786
                        </div>
                        <div class="content">
                            <img class="ui avatar image" src="{% static 'Fusion/img/zlatan.jpg' %}">
                            <a class="ui header">Atul Gupta</a>
                        </div>
                        <div class="ui divider"></div>
                    </div>


                    <div class="item">
                        <div class="right floated tiny teal ui button">
                            <i class="mail icon"></i>Send Mail
                        </div>
                        <div class="right floated tiny blue ui button hidden-phone">
                            <i class="phone icon"></i>773-338-7786
                        </div>
                        <div class="content">
                            <img class="ui avatar image" src="{% static 'Fusion/img/zlatan.jpg' %}">
                            <a class="ui header">Atul Gupta</a>
                        </div>
                        <div class="ui divider"></div>
                    </div>


                    <div class="item">
                        <div class="right floated tiny teal ui button">
                            <i class="mail icon"></i>Send Mail
                        </div>
                        <div class="right floated tiny blue ui button hidden-phone">
                            <i class="phone icon"></i>773-338-7786
                        </div>
                        <div class="content">
                            <img class="ui avatar image" src="{% static 'Fusion/img/zlatan.jpg' %}">
                            <a class="ui header">Atul Gupta</a>
                        </div>
                        <div class="ui divider"></div>
                    </div>

                </div>

                <div class="ui bottom attached tab segment" data-tab="second">
                    <div class="ui fluid icon input">
                        <input placeholder="Search ..." type="text">
                        <i class="search icon"></i>
                    </div>

                    <div class="ui divider"></div>

                    <div class="item">
                        <div class="right floated tiny teal ui button">
                            <i class="mail icon"></i>Send Mail
                        </div>
                        <div class="right floated tiny blue ui button hidden-phone">
                            <i class="phone icon"></i>773-338-7786
                        </div>
                        <div class="content">
                            <img class="ui avatar image" src="{% static 'Fusion/img/zlatan.jpg' %}">
                            <a class="ui header">Atul Gupta</a>
                        </div>
                        <div class="ui divider"></div>
                    </div>
                </div>

        </div>
    </div>
    {% comment %}The Modules ends here!{% endcomment %}
{% endblock %}

FusionIIIT-master/FusionIIIT-master/FusionIIIT/templates/dashboard/modules.html
{% load static %}

{% block modules %}
{% comment %}The Modules start here!{% endcomment %}
    <div class="stackable doubling ui internally celled grid">
        <div class="column">
            <div class="ui fluid card" style="padding-top: 12px; padding-bottom: 24px; max-width: 18vw;">
                <a class="ui top attached black label">
                    <span class="ui inverted header">Modules</span>
                    <i class="setting icon right floated"></i>
                    <i class="chevron up icon right floated" id="toggleIcon" onclick="toggleContent()"></i>
                </a>

                <div class="content modulesContent">
                    <div class="ui two column stackable doubling grid">
                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}

                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}

                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}

                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}

                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}
                    </div>
                </div>

{% comment %}
                <a class="ui bottom attached blue label">
                    <i class="right arrow icon right floated"></i>
                </a>
{% endcomment %}
            </div>
        </div>
    </div>
    {% comment %}The Modules End here!{% endcomment %}
{% endblock %}

FusionIIIT-master/FusionIIIT-master/FusionIIIT/templates/dashboard/navbar.html
{% load static %}

{% block navBar %}
    {% include 'dashboard/sidenavbar.html' %}

    <div>
        <div class="ui stackable massive inverted top attached menu" id="navbar">
            <a class="item" id="sidebartrigger">
                <i class="sidebar icon"></i>
            </a>
            <a class="item" href="{% url 'globals:index' %}" >
                <span>
                    Fusion!
                </span>
            </a>

            <a class="item" href="{% url 'globals:dashboard' %}">
                <i class="ui active inverted large home icon"></i>
                Dashboard
            </a>

            <div class="right inverted menu">
                <a class="item" href="{% url 'eis:profile' %}">
                    {% comment %}
                        TODO: User details! depending on type of user say: STUDENT/FACULTY/STAFF!
                    {% endcomment %}
                    <img class="ui avatar image" src="{% static 'globals/img/zlatan.jpg' %}">
                    Atul Gupta
                </a>

                <div class="ui dropdown icon item">
                    <i class="settings icon"></i>
                    <div class="menu">
                        <div class="item">
                            <i class="dropdown icon"></i>
                            <span class="text">New</span>
                            <div class="menu">
                                <div class="item">Document</div>
                                <div class="item">Image</div>
                            </div>
                        </div>
                        <div class="item">
                            Open...
                        </div>
                        <div class="item">
                            Save...
                        </div>
                        <div class="item">Edit Permissions</div>
                        <div class="divider"></div>
                        <div class="header">
                            Export
                        </div>
                        <div class="item">
                            Share...
                        </div>
                    </div>

                </div>

                <div class="item">
                    <i class="icon mail"></i>
                    <div class="ui red label">22</div>
                </div>

                <div class="item">
                    <i class="alarm icon"></i>
                    <div class="ui teal label">22</div>
                </div>

                <a class="right item" href="">
                    {% comment %}
                        TODO: Whatever!
                    {% endcomment %}
                    <i class="ui inverted sign out icon"></i>
                    Logout
                </a>

            </div>
        </div>

        <div class="ui divider"></div>


    {% block data%}
    {% endblock %}



    </div>
{% endblock %}

FusionIIIT-master/FusionIIIT-master/FusionIIIT/templates/dashboard/sidenavbar.html
{% load static %}

{% block sidenav %}
    <div class="ui sidebar inverted vertical menu">
        <div class="ui doubling stackable grid container">

            <div class="ui inverted centered raised item"></div>

            {% comment %}The User Item starts here!{% endcomment %}
            <div class="ui inverted centered raised item">
                <img src="{% static 'globals/img/zlatan.jpg' %}" class="ui small circular centered image">

                <br>

                <div class="ui bottom attached inverted" style="text-align: center;">
                    {% comment %}
                        TODO: User Details!
                    {% endcomment %}
                    <h2 class="ui inverted header">Dr. Atul Gupta</h2>
                    <span class="ui inverted meta">Associate Professor</span>
                </div>

            </div>
            {% comment %}The User Item ends here!{% endcomment %}

            <div class="ui divider inverted"></div>

            {% comment %}The Modules Accordian starts here!{% endcomment %}
            <div class="ui vertical inverted accordion fluid menu" style="margin-bottom: 24px;">
                <div class="item">
                    <a class="active title">
                        <i class="dropdown icon"></i>
                        <span class="ui inverted header">
                            Modules
                        </span>
                    </a>
                    <div class="active content">
                        <div class="link items">
                            <a class="item" href="{% url 'complaint:complaint' %}">
                                <h4>Complaint Module</h4>
                            </a>

                            <a class="item" href="{% url 'mess:mess' %}">
                                <h4>Central Mess Module</h4>
                            </a>

                            <a class="item" href="{% url 'leave:leave' %}">
                                <h4>Leave Module</h4>
                            </a>

                            <a class="item" href="{% url 'placement:placement' %}">
                                <h4>Placement Module</h4>
                            </a>

                            <a class="item" href="{% url 'visitorhostel:visitorhostel' %}">
                                <h4>Visitor Hostel Module</h4>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% comment %}The Modules Accordian ends here!{% endcomment %}

            {% comment %}The Profile Item starts here!{% endcomment %}
            <a class="centered raised item" href="{% url 'eis:profile'%}">
                <span class="inverted header">Profile</span>
                <i class="large inverted user icon right floated"></i>
            </a>
            {% comment %}The email Item ends here!{% endcomment %}

            {% comment %}The email Item starts here!{% endcomment %}
            <div class="centered raised item">
                <span class="inverted header">Emails</span>
                <i class="large inverted mail icon right floated"></i>
            </div>
            {% comment %}The email Item ends here!{% endcomment %}

            {% comment %}The Webpage Item starts here!{% endcomment %}
            <div class="centered raised item">
                <span class="inverted header">Webpage</span>
                <i class="large inverted external icon right floated"></i>
            </div>
            {% comment %}The Webpage Item ends here!{% endcomment %}

            {% comment %}The Activity Log Item starts here!{% endcomment %}
            <div class="centered raised item">
                <span class="inverted header">Activity Log</span>
                <i class="large inverted area chart icon right floated"></i>
            </div>
            {% comment %}The Activity Log Item ends here!{% endcomment %}

            {% comment %}The Logout Item starts here!{% endcomment %}
            <div class="centered raised item">
                <span class="inverted header">Logout</span>
                <i class="large inverted sign out icon right floated"></i>
            </div>
            <div class="item"></div>
            {% comment %}The Logout Item ends here!{% endcomment %}

        </div>
    </div>

{% endblock %}